log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-k0s.0
      # renovate: datasource=github-releases depName=k0sproject/k0s versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\+k0s\.(?<build>\d+)$
      k0s_version: v1.34.3+k0s.0
      k0s_sha_amd64: a92451e3c876d9d76db42b722bcc3a0c5b875f2353fe5401b8e25018da69b838
      k0s_sha_arm64: a06728518e01ab7d986ad4fff1c608ac7e48da72e133e8a2a638115af6548277
      # renovate: datasource=github-releases depName=k0sproject/k0sctl versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      k0sctl_version: v0.28.0
      k0sctl_sha_amd64: 30776867c60a02f29edae7f8bb2eb72f48bd09392fe7b6cebb26d4dcb71ab33c
      k0sctl_sha_arm64: 1a6604c90231db1684835b2aa087c93bd504bc0def3b9e79958a123682eea24c
      # renovate: datasource=docker depName=quay.io/cilium/charts/cilium versioning=regex:^v?(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      cilium_chart_version: 1.19.1
      # renovate: datasource=github-releases depName=cilium/cilium-cli versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      cilium_cli_version: v0.19.1
