log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-k0s.0
      # renovate: datasource=github-releases depName=k0sproject/k0s versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\+k0s\.(?<build>\d+)$
      k0s_version: v1.35.1+k0s.0
      k0s_sha_amd64: a65ce7cc1a0645dfce517c582a875a14b9660b5913abfee4c0edf3dc7e169e78
      k0s_sha_arm64: 2a66e1e369751a02824f9a572a6e2739b9a93adfc49772fccf1cf0345553bd80
      # renovate: datasource=github-releases depName=k0sproject/k0sctl versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      k0sctl_version: v0.28.0
      k0sctl_sha_amd64: 30776867c60a02f29edae7f8bb2eb72f48bd09392fe7b6cebb26d4dcb71ab33c
      k0sctl_sha_arm64: 1a6604c90231db1684835b2aa087c93bd504bc0def3b9e79958a123682eea24c
      # renovate: datasource=docker depName=quay.io/cilium/charts/cilium versioning=regex:^v?(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      cilium_chart_version: 1.19.1
      # renovate: datasource=github-releases depName=cilium/cilium-cli versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      cilium_cli_version: v0.19.2
