---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json
image:
  useDigest: false
envoy:
  image:
    useDigest: false
operator:
  image:
    useDigest: false
hubble:
  ui:
    enabled: true
    frontend:
      image:
        useDigest: false
    backend:
      image:
        useDigest: false
  relay:
    enabled: true
    image:
      useDigest: false
